More actions
gcala/pacmanlogviewer pull request #5
Opened 2019-11-21 16:31 UTC by chrisjbillington

Add the downgrade and reinstall actions.

Since there was not really a good choice of a "reinstalled" icon that was not easily confused with the existing "upgraded" one, I've changed upgrade to an up arrow, and made downgrade a down arrow and reinstall the refresh icon (i.e. the icon previously used for upgrade).

This PR is based on top of the branch for PR #4 (since it modifies the regex on the same line as that one so wouldn't merge cleanly), but if you decide not to merge PR #4 I can rejig this one to be based off master.

![image](https://user-images.githubusercontent.com/1044087/69356847-1e189300-0c52-11ea-80ae-0de6700b9cba.png)

2020-02-03 15:19 UTC, chrisjbillington commented
Rebased now that #4 is merged - this PR now only contains the actual changes for adding more actions

2021-02-21 05:11 UTC, chrisjbillington commented
Rebased onto the latest master.

Any interest in merging?

2021-05-09 17:43 UTC, biloucat commented
Thank-you
I have made a PKGBUILD from your version for my personal use !

2023-02-01 08:31 UTC, vedgy requested changes
Other than the two minor issues, the new feature looks good and works well. Thanks!

2023-02-01 08:31 UTC, vedgy commented on dialog.cpp
> +    settings.setValue("Filters/ShowReinstalled", ui->FltrsWidget->reinstalledChecked());
The added settings should be used in `Dialog::loadSettings()` so that the checked states are preserved after restarting the application.

2023-02-01 08:31 UTC, vedgy commented on dialog.cpp
>      else
The regex in `Dialog::readPacmanLogFile()` already ensures that one of the operation strings is present: `(installed|removed|upgraded|downgraded|reinstalled)`. So this else and the next line `filter += "AND (op!='installed' AND op!='upgraded' AND op!='removed')";` can be safely removed. Currently unchecking all checkboxes shows downgraded and reinstalled packages.

2023-02-01 09:02 UTC, vedgy commented
As the final touches:
1. The unused file *defines.h*, which misses the newly added actions, can be removed along with its single mention in *pacmanlogviewer.pro*.
2. *README.md* can be updated to mention downgrading and reinstalling along with the existing 3 operations.

2023-02-01 10:01 UTC, chrisjbillington commented
Thanks for the review! The changes pointed out have been made, and I updated the README and removed the unused `defines.h` and its mention.

2023-02-01 13:11 UTC, vedgy commented
The fix looks good perfect to me now. Thanks.

The two commits could be squashed into one if/when this pull request is accepted.

Note: SQLite should be able to notice `"AND FALSE"` at the end of the query and optimize according to [answers to this SO question](https://stackoverflow.com/questions/49861513/does-sqlite-optimize-a-query-with-multiple-and-conditions-in-the-where-clause). So I don't think the filter string needs to be optimized manually.

2023-02-01 13:11 UTC, vedgy approved these changes

2023-02-11 10:03 UTC, gcala approved these changes
It's fine for me!

2023-02-11 10:03 UTC, merged